plugins {
	id 'java'
    id 'application'
}

def javafxSdkPath = "/Users/xuxuh/Desktop/JAVAFX/javafx-sdk-22/lib/"  // <- Replace this!
def os = org.gradle.internal.os.OperatingSystem.current()

def platform = ''
if (os.isMacOsX()) {
    platform = System.getProperty("os.arch") == "aarch64" ? "mac-aarch64" : "mac"
}

repositories {
    mavenCentral()
}

def javafxVersion = '22.0.2' // Use latest stable version

dependencies {
    implementation 'org.json:json:20230618'
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.1' // or latest version
    testImplementation 'org.testfx:testfx-junit5:4.0.16-alpha'

    implementation "org.openjfx:javafx-controls:$javafxVersion:$platform"
	implementation "org.openjfx:javafx-fxml:$javafxVersion:$platform"
	implementation "org.openjfx:javafx-base:$javafxVersion:$platform"
	implementation "org.openjfx:javafx-graphics:$javafxVersion:$platform"

	testImplementation "org.openjfx:javafx-controls:$javafxVersion:$platform"
	testImplementation "org.openjfx:javafx-fxml:$javafxVersion:$platform"
	testImplementation "org.openjfx:javafx-base:$javafxVersion:$platform"
	testImplementation "org.openjfx:javafx-graphics:$javafxVersion:$platform"
}

application {
    mainClass = 'main.java.server.ChessServer'  // replace with your main class
}

run {
    doFirst {
        jvmArgs = [
            "--module-path", javafxSdkPath,
            "--add-modules", "javafx.controls,javafx.fxml"
        ]
    }
}

task runClient(type: JavaExec) {
  classpath = sourceSets.main.runtimeClasspath
  description = "Run Client"
  mainClass.set('client.ChessClient') 
  args 'localhost', '8888'
    jvmArgs = [
        '--module-path', classpath.asPath,
        '--add-modules', 'javafx.controls,javafx.fxml'
    ]
}

task runServer(type: JavaExec) {
  classpath = sourceSets.main.runtimeClasspath
  description = "Run Server"
  mainClass.set('server.ChessServer')
  args '8888'
    jvmArgs = [
        '--module-path', classpath.asPath,
        '--add-modules', 'javafx.controls,javafx.fxml'
    ]
}

test {
    useJUnitPlatform()

    jvmArgs = [
        '--module-path', classpath.asPath,
        '--add-modules', 'javafx.controls,javafx.fxml',
        '-Dtestfx.robot=glass',
        '-Dtestfx.headless=true',
        '-Dprism.order=sw',
        '-Dprism.text=t2k'
    ]

    // Exclude the specific test class (adjust the path if needed)
    exclude '**/logic/statemachine/SelectionControllerTest.class'
}

